#!/usr/bin/env bash
#say hi
i=1
 while [  $i -le 10 ]; do
	    if [ $i -eq 9 ]; then

		         echo "Hi"
			      else
				             echo "Best School"



					        fi

						   #echo "Best School"
						      i=$((i+1))

						       done
