#!/usr/bin/env bash
#bad luck from China
i=1
 while [  $i -le 20 ]; do
   
   if [ 5 -eq $i ]; then
     echo "bad luck from China"
     elif [ 10 -eq $i ]; then
       echo "bad luck from Japan"
       elif [ 18 -eq $i ]; then
         echo "bad luck from Italy"

         
       
   fi
   
   echo "$i"
   i=$((i+1))


 done
