#!/usr/bin/env bash
#trail
touch /var/run/myscript.pid


for (( i = 10; i > 0; i++ )); do
  echo "To infinity and beyond"
  trap "echo I hate the kill command; exit" 0 15
  trap "echo Y U no love me?!" 0 2
  file=/var/run/myscript.pid
  trap "rm -f $file; exit" 0 3 15

done
